* diceware-generator

FIXME: Write a one-line description of your library/project.

** Overview

FIXME: Write a paragraph about the library/project and highlight its goals.

** Setup

To get an interactive development environment run:

    lein figwheel

    lein ring server

and open your browser at [localhost:3449](http://localhost:3449/).
This will auto compile and send all changes to the browser without the
need to reload. After the compilation process is complete, you will
get a Browser Connected REPL. An easy way to try it is:

    (js/alert "Am I connected?")

and you should see an alert in the browser window.

To clean all compiled files:

    lein clean

To create a production build run:

    lein do clean, cljsbuild once min

    lein with-profile -dev,+production uberjar

    java $JVM_OPTS -cp target/diceware-generator.jar clojure.main -m diceware-generator.server

    heroku local web

    git push heroku master

    heroku open

And open your browser in `resources/public/index.html`. You will not
get live reloading, nor a REPL.

This project was created with:

     lein new figwheel diceware-generator -- --reagent

     heroku create

** License

Copyright © 2014 FIXME

Distributed under the Eclipse Public License either version 1.0 or (at your option) any later version.
